apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
- name: cert-manager
  url: https://charts.jetstack.io
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
- name: grafana
  url: https://grafana.github.io/helm-charts
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
- name: argo
  url: https://argoproj.github.io/argo-helm
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
- name: external-secrets
  url: https://charts.external-secrets.io
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server/
  caFile: ""
  certFile: ""
  keyFile: ""
  insecure_skip_tls_verify: false
  pass_credentials_all: false
  username: ""
  password: ""
